### ISSUE TITLE
mute_xiaoai 设置true，但是仍然回复

### ISSUE THREAD

**Issue by lanayalouisforever** [yihong0618/MiService#11]
这个mute_xiaoai参数，设置true后，使用关键字提问题，小爱同学本身还是会回答大约5-7个字才停止。
效果上和发送一个无法播放的文字来打断正在播放是一样的。
是我操作问题吗？有没有真正意义上的不让小爱回复。
使用静音来间接达到效果，但是也是伪静音，只是声音很小而已。

**Comment by yihong0618** [comment]
有办法，但不推荐，会不断请求，你可以改代码里的 sleep 时间
