### ISSUE TITLE
小爱播放音乐api求助

### ISSUE THREAD

**Issue by TheStarFlow** [yihong0618/MiService#12]
该如何正确运行让小爱可以播放 音乐的 url 。
执行 micli.py play http://example.mp3， 返回 -704220025
thx。

**Comment by yihong0618** [comment]
你的小爱型号是，有的不支持，在 xiaogpt readme 里列出的是不支持的

**Comment by TheStarFlow** [comment]
> 你的小爱型号是，有的不支持，在 xiaogpt readme 里列出的是不支持的

lx06 和 l05c 都试过， tts 能力都ok。播放 url 却都返回 -704220025

**Comment by TheStarFlow** [comment]
> > 你的小爱型号是，有的不支持，在 xiaogpt readme 里列出的是不支持的
> 
> lx06 和 l05c 都试过， tts 能力都ok。播放 url 却都返回 -704220025 

抱歉是我不严谨了，拿了原fork的代码来测试，播放没问题的。
