### ISSUE TITLE
[小米小爱音箱Play 增强版] 查询型号

### ISSUE THREAD

**Issue by wushuzh** [yihong0618/MiService#15]
执行 mina ，没有获得结果 ？

```
(venv) $ micli mina

(venv) $
```

**Comment by yihong0618** [comment]
micli list 有么？

**Comment by llanozero** [comment]
Windows命令行下执行micli list 后，我也没有没有显示，单独运行micli.py,出现如下截图结果，
<img width="960" alt="微信图片_20240127222500" src="https://github.com/yihong0618/MiService/assets/144093894/bf115ef1-4cae-40b7-88c5-97a83d2e7494">
分析可能得原因：内部会不会默认执行export MI_USER=<username>，而Windows命令行工具只能识别“set”。我不知道在哪里可以修改。

**Comment by yihong0618** [comment]
@llanozero 参考 https://github.com/yihong0618/xiaogpt 的 README

**Comment by llanozero** [comment]
这里在管理员模式下仍然只返回了空行。@yihong0618

![微信截图_20240127234722](https://github.com/yihong0618/MiService/assets/144093894/1b5f4e5b-3e17-4289-96d8-59962bfd6cc5)

**Comment by llanozero** [comment]
G:\xiaogpt-main\code\20240127\MiService-main>micli list
Exception on login <#USERNAME#:> 'userId'
Traceback (most recent call last):
  File "F:\ProgramData\Python\Python311\Lib\site-packages\miservice\miaccount.py", line 71, in login
    self.token["userId"] = resp["userId"]
                           ~~~~^^^^^^^^^^
KeyError: 'userId'
G:\xiaogpt-main\code\20240127\MiService-main>

之前也出现过如上报错，后来我关闭代理并且在本地浏览器上登录过https://account.xiaomi.com/网站后，再次执行micli list
上述报错消失，而取而代之的是空行“/n”。

**Comment by yihong0618** [comment]
你进米家的那个 app 看看有没有绑定上

**Comment by xiaomaailuohui** [comment]
我也是遇到了同样的问题，至今尚未解决。
-------------------------------------------------------
设备：小爱音箱play增强版
工具：windows PowerShell
问题：获取did，不报错也不返回任何东西、
---------------------------------------------------------
已实施措施：
1、powershell换成cmd（无效）
2、家庭网络换成手机热点（无效）
3、米家APP重新绑定音箱（无效）
4、路径换成纯英文路径（无效）
5、电脑网页登录小米账号（无效）
6、重启电脑（无效）
-------------------------------------------------------------------------------------
先说一下我的操作过程：
1、Set-ExecutionPolicy -ExecutionPolicy RemoteSigned（使用开放策略）
2、python -m venv venv（创建环境）
3、venv\Scripts\activate（激活环境）
4、pip install -U miservice_fork（安装依赖）
5、$env:MI_USER="6xxxxx"（设置账号）
6、$env:MI_PASS="mxxxxxxxx"（设置密码）
7、python micli.py list（获取did，但是什么都不返回）
![1](https://github.com/yihong0618/MiService/assets/100980632/fa0d2048-b029-4e5b-85d3-c9a4fa65f277)

**Comment by RoCry** [comment]
我跟楼上一样, list 的结果是空

**Comment by yihong0618** [comment]
@RoCry @xiaomaailuohui @llanozero @wushuzh 

修复了，我把打印不注意删掉了抱歉。


pip install -U miservice-fork 来试试

**Comment by RoCry** [comment]
> @RoCry @xiaomaailuohui @llanozero @wushuzh
> 
> 修复了，我把打印不注意删掉了抱歉。
> 
> pip install -U miservice-fork 来试试

测试可以了 赞一个响应速度

**Comment by xiaomaailuohui** [comment]
感谢博主，目前确实可以了，已经获取到了设备列表。
解决方法：
1、重新下载MiService压缩包
2、按照以前步骤来就可以了。
--------------------------------------------------------------------------
（悄咪咪的说一句，老哥确实很认真的对待每一个人的问题，今天刚提问，就得到了解决，感谢）
![image](https://github.com/yihong0618/MiService/assets/100980632/9d443ce9-4b38-4851-90ad-1f1708ab17ec)

**Comment by yihong0618** [comment]
> ## 感谢博主，目前确实可以了，已经获取到了设备列表。
> 解决方法：
> 1、重新下载MiService压缩包
> 2、按照以前步骤来就可以了。
> （悄咪咪的说一句，老哥确实很认真的对待每一个人的问题，今天刚提问，就得到了解决，感谢） ![image](https://private-user-images.githubusercontent.com/100980632/300395416-9d443ce9-4b38-4851-90ad-1f1708ab17ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY1MTkzNjQsIm5iZiI6MTcwNjUxOTA2NCwicGF0aCI6Ii8xMDA5ODA2MzIvMzAwMzk1NDE2LTlkNDQzY2U5LTRiMzgtNDg1MS05MGFkLTFmMTcwOGFiMTdlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyOVQwOTA0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lOWY1Nzc5NTNiNTJlY2I1ZjYzNTFkMmNjZDFiZTBlNTdkNGFmZGQ3NzVkMjUzNmFiNjIwZWZkZTIwNjljYTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ATBpZSJAK0Ws4nmk3zRgbChORj84NwWPKKVmhsBA-ew)

不客气

**Comment by yihong0618** [comment]
关了哈

**Comment by xiao-mantou** [comment]
@yihong0618
``Exception: we have no hardware: MDZ-25-DA please use `micli mina` to check``
你好，我的设备上的型号不对，micli list输出正常，micli mina输出空行

**Comment by yihong0618** [comment]
> @yihong0618 `` Exception: we have no hardware: MDZ-25-DA please use `micli mina` to check `` 你好，我的设备上的型号不对，micli list输出正常，micli mina输出空行

这个型号不支持 mina

**Comment by xiao-mantou** [comment]
> > @yihong0618 `` Exception: we have no hardware: MDZ-25-DA please use `micli mina` to check `` 你好，我的设备上的型号不对，micli list输出正常，micli mina输出空行
> 
> 这个型号不支持 mina

意思是在这个型号无法实现xiaogpt吗?
