### ISSUE TITLE
请问如何控制播放一个URL列表？

### ISSUE THREAD

**Issue by creke** [yihong0618/MiService#16]
请问如何控制播放一个URL列表？

**Comment by yihong0618** [comment]
这个有点难度，等我有时间写一下。你要自己做的话思路是

1. 得拿到 url.mp3 的时长，这个就非常有难度了，需要写算法
2. 之后就是一个 url_list
3. for u in urllist -> play sleep(duration)

**Comment by creke** [comment]
感谢！
使用play实现的话无法控制上一首下一首，我了解到有个play album的接口，请问预计是使用这个能力来实现吗？

**Comment by yihong0618** [comment]
> 感谢！ 使用play_by_url实现的话无法控制上一首下一首，我了解到有个play album的接口，请问预计是使用这个能力来实现吗？

那个不行。那个 play 的是 qq 音乐的

**Comment by creke** [comment]
了解，请问预计也是基于mp3时长来控制play_by_url吗？还是有其他思路哈？

**Comment by yihong0618** [comment]
> 了解，请问预计也是基于mp3时长来控制play_by_url吗？还是有其他思路哈？

是的

**Comment by yihong0618** [comment]
@creke 

支持了

多了两个命令，请尝试

pip install -U miservice-fork

```cli
micli loop ${mp3_url}  # 循环播放
micli pause

# make a playlist name test.txt
cat test.txt
# http://192.168.6.212:8000/public/s4.mp3
# http://192.168.6.212:8000/public/s1.mp3
# http://192.168.6.212:8000/public/s2.mp3
# http://193.168.6.212:8000/public/s3.mp3

micli play_list test.txt # play the list
```

**Comment by yihong0618** [comment]
@creke 目前不太完善，PR welcome 哈

**Comment by LetMeFly666** [comment]
> 这个有点难度，等我有时间写一下。你要自己做的话思路是
> 
> 1. 得拿到 url.mp3 的时长，这个就非常有难度了，需要写算法
> 2. 之后就是一个 url_list
> 3. for u in urllist -> play sleep(duration)

yihong大佬，虽然还没有尝试（没有搭建起来音乐server），但是播放途中暂停的话可能会出现一些问题？

（也许是我多虑了

**Comment by yihong0618** [comment]
> > 这个有点难度，等我有时间写一下。你要自己做的话思路是
> > 
> > 1. 得拿到 url.mp3 的时长，这个就非常有难度了，需要写算法
> > 2. 之后就是一个 url_list
> > 3. for u in urllist -> play sleep(duration)
> 
> yihong大佬，虽然还没有尝试（没有搭建起来音乐server），但是播放途中暂停的话可能会出现一些问题？
> 
> （也许是我多虑了

没明白。理论没问题
