### ISSUE TITLE
如果有搞前端的想获取 did，可以用这个仓库，是在 js 下实现的，亲测很轻松就获取到 did 了，适合不熟悉 python 的人操作

### ISSUE THREAD

**Issue by kmq116** [yihong0618/MiService#17]
https://github.com/inu1255/mi-service

**Comment by yihong0618** [comment]
hi, 用 python 的版本有什么报错么？

**Comment by kmq116** [comment]
> hi, 用 python 的版本有什么报错么？

不好意思 hong 哥，我之前提了个 issue，后来感觉提 issue 有点伸手党，就给关了，然后自己去找解决办法，解决了之后，就想分享下解决办法，所以现在这个 issue 看起来比较不礼貌，抱歉啦
我遇见的问题是这样的
在 windows 下运行，尝试获取 did 的时候，报这个错误
![image](https://github.com/yihong0618/MiService/assets/59247607/48d2785f-8183-46d6-b400-d266e76afb71)
https://github.com/yihong0618/MiService/issues/2#issuecomment-1522922050
自己分析是这个 python 脚本在 windows 下的异常，像是个类型错误，然后就没提

**Comment by yihong0618** [comment]
@kmq116 谢谢，我来研究下。

**Comment by yihong0618** [comment]
> > hi, 用 python 的版本有什么报错么？
> 
> 不好意思 hong 哥，我之前提了个 issue，后来感觉提 issue 有点伸手党，就给关了，然后自己去找解决办法，解决了之后，就想分享下解决办法，所以现在这个 issue 看起来比较不礼貌，抱歉啦 我遇见的问题是这样的 在 windows 下运行，尝试获取 did 的时候，报这个错误 ![image](https://private-user-images.githubusercontent.com/59247607/298270012-48d2785f-8183-46d6-b400-d266e76afb71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3Mzg0OTgsIm5iZiI6MTcwNTczODE5OCwicGF0aCI6Ii81OTI0NzYwNy8yOTgyNzAwMTItNDhkMjc4NWYtODE4My00NmQ2LWI0MDAtZDI2NmU3NmFmYjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDA4MDk1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiN2M4NTNhNWE4M2UxNWM4YzM3ODc1OWM3ODNhNGRkZTA1Nzc0NjhhY2ZkYTRkNDE4Zjc4NDYxOWE4NjVjYTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z2FC8SrCu3YNeexIBBIjK1n2OXuoe11GqsBKINwB2zQ) [#2 (comment)](https://github.com/yihong0618/MiService/issues/2#issuecomment-1522922050) 自己分析是这个 python 脚本在 windows 下的异常，像是个类型错误，自己不熟 py 的语法，然后就没提

看起来是没设置 windows 的密码，windows 和 linux 不一致，你可以参考 xiaogpt https://github.com/yihong0618/xiaogpt readme 来设置

**Comment by kmq116** [comment]
> @kmq116 谢谢，我来研究下。

后面我获取到 did 之后，在使用 gpt3 的时候，gpt 回复的代码，也报了个类型错误，已经定位到代码的问题是这块，，等晚上我再复现下，去 xiaogpt 提个 issue
![image](https://github.com/yihong0618/MiService/assets/59247607/5a5fe3da-0890-4009-9fbc-1a764ebaafc3)
也是一样的 config.gpt_options 在 null 上不存在，大概是这么个异常，能力有限，没法贡献 py 代码
https://github.com/yihong0618/xiaogpt/blob/11b5c3ae3801a810cffb9abf94f43b2f0c7787e6/xiaogpt/xiaogpt.py#L282

**Comment by yihong0618** [comment]
@kmq116 必要用 gpt3 这个我们可能之后会下了，兼用用 chatgpt
python xiaogpt.py --hardware LX06 --account xxxxx--password xxxxx ----use_chatgpt_api  --openai_key xxxxx --mute_xiaoai --stream --tts edge

用类似这样的命令试试

**Comment by kmq116** [comment]
> @kmq116 必要用 gpt3 这个我们可能之后会下了，建议用 chatgpt python xiaogpt.py --hardware(硬件) LX06 --account xxxxx--password(密码) xxxxx ----use_chatgpt_api --openai_key(关键) xxxxx --mute(静音)_xiaoai --stream(流) --tts edge(边缘)
> 
> 用类似这样的命令试试

👌ok，我下班去试试

**Comment by yihong0618** [comment]
先关了哈
