### ISSUE TITLE
小爱音箱适配问题

### ISSUE THREAD

**Issue by njtyair** [yihong0618/MiService#21]
micli的play方法播放音乐，是否有音箱型号的限制？目前小爱触屏音箱无法使用，信号lx04

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by hanxi** [comment]
player_play_music 接口抓包有新的进展，在我的 LX07A 上能播放本地歌曲。有别的型号抓包也是用的 player_play_music 接口，所以我想新增一个接口，还没想好接口名字，或者用旧接口名字加个参数也行。 @yihong0618 帮忙给点建议？ok 的话我可以提个 pr 。

> https://github.com/hanxi/xiaomusic/issues/49

**Comment by yihong0618** [comment]
我觉得保留原接口下面写判断好一点。

```python
player_play_music():
    if device in ['a', 'b', 'c']:
        do()
    else:
        do_other()
```

**Comment by hanxi** [comment]
好的

**Comment by hanxi** [comment]
这个库里如何拿到device呢？xiaogpt才有hardware，否则只能先调用 device_list 缓存deviceid对应hardware的关系了。这样是不是又复杂化了。

**Comment by yihong0618** [comment]
参考 cli.py

**Comment by hanxi** [comment]
目前 LX04  X10A  X08A 还无法播放，需要再想想办法。

**Comment by hanxi** [comment]
同步最新消息，触屏版播放有希望了，等明天大部分型号测试正常了我再提个 pr 吧，主要是补充几个参数，已经精简到不能再精简了。相关提交见 https://github.com/hanxi/xiaomusic/commit/e97639302f4a3ace48a6f300ef8acd99c15a519a

**Comment by hanxi** [comment]
@yihong0618 发现之前的实现不是很好，每次发现不能播放的设备都要加一下。有没有更好的建议？还是我发现一个类型就提一次pr?比如现在收到反馈X08C触屏版用新接口可以播放。

**Comment by yihong0618** [comment]
> @yihong0618 发现之前的实现不是很好，每次发现不能播放的设备都要加一下。有没有更好的建议？还是我发现一个类型就提一次pr?比如现在收到反馈X08C触屏版用新接口可以播放。

hack 项目只能如此我觉得没啥问题，定期更新下就行
