### ISSUE TITLE
执行./micli.py list报错

### ISSUE THREAD

**Issue by luoly601** [yihong0618/MiService#3]
![image](https://user-images.githubusercontent.com/96689189/228508246-f11c2e7e-08f8-49df-9328-ea72176f2c75.png)
执行报错如下
./micli.py: line 1: from: command not found
./micli.py: line 6: syntax error: unexpected end of file
求解，谢谢

**Comment by luoly601** [comment]
是登录小米账号吧？

**Comment by eggcaker** [comment]
如果是linux环境，直接用micli ,不要用micli.py

**Comment by jjiikkkk** [comment]
如果是linux环境，直接用micli ,不要用micli.py  根本不认micli

**Comment by jjiikkkk** [comment]
我用了三个人github上的方法，基本上也是互相改造的，主要的问题都是小米账号过不去，而且有多个人也是过不去
从国外的云服务器换到了国内的云服务器，过不去
忙活了好几天了，线上的SSH，到本地的SSH，现在让我换linux for windows
都会出现micli的问题，都会出现path的问题，解决掉了，但是还是验证过去不，小米的账号都去小米手机里认证实名拍照和加了银行卡

**Comment by kylezhang** [comment]
在`./micli.py`的开头加上 python 的 shell 标识，我是python3
```
#!/usr/bin/env python3
from miservice.cli import micli


if __name__ == "__main__":
    micli()

```

<img width="386" alt="image" src="https://user-images.githubusercontent.com/3679798/231929170-491d8cfc-6e09-4331-b260-85b81a0a90d1.png">


参考链接：https://stackoverflow.com/questions/16069816/getting-python-error-from-cant-read-var-mail-bio

**Comment by jjiikkkk** [comment]
不是特别看得懂，可以试试，如果是这样 海外的云服务器可以过吗
否则国内云服务器就算通了 里面还是要插入代理
