### ISSUE TITLE
播放音乐时蓝色灯常亮问题

### ISSUE THREAD

**Issue by hanxi** [yihong0618/MiService#30]
更新到最新版本测试了我的红米音箱灯还是会常量。 另外请问 player_play_url 方法是通过什么操作抓到的接口呢？我在小爱音箱 app 里播放音乐和故事都是触发的 player_play_music 方法。

**Comment by yihong0618** [comment]
- 没法抓到接口
- 问题我今天看看。蓝灯常亮有个解决办法，叫一下小爱同学，然后他说的时候再让他停止播放

**Comment by yihong0618** [comment]
测试了下我这里没有，你把那个参数改回去试试？

**Comment by hanxi** [comment]
可能是我的硬件问题吧，我用原生的播放音乐也会有灯，不过亮度会暗一点。

**Comment by hanxi** [comment]
> 测试了下我这里没有，你把那个参数改回去试试？

试了改0和1都是一样的，是蓝灯和绿灯呼吸变换亮着。用小爱音箱app播放是绿灯呼吸亮着。

**Comment by yihong0618** [comment]
改成2试试

**Comment by hanxi** [comment]
> 改成2试试

改成2可以关灯。

**Comment by yihong0618** [comment]
彻底研究一下来个 PR? 
我猜测是型号不同参数不同

**Comment by hanxi** [comment]
> 彻底研究一下来个 PR? 我猜测是型号不同参数不同

我只有一个设备，按设备类型配置不同的参数吗？未验证的给默认参数1?

**Comment by yihong0618** [comment]
我觉得可以都给 2, 我们可以把这个变成个可变参数

**Comment by hanxi** [comment]
> 我觉得可以都给 2, 我们可以把这个变成个可变参数

那变成参数比较简单，我改下提个pr吧。
