### ISSUE TITLE
获取不到歌曲播放时长问题

### ISSUE THREAD

**Issue by hanxi** [yihong0618/MiService#34]
1. 目前的写法只支持 mp3 格式。
2. 这个链接 <https://m10.music.126.net/20240626132818/150ef0d02b16497727218fbc4046e46c/ymusic/5353/0f0f/0358/d99739615f8e5153d77042092f07fd77.mp3> 的歌曲会取不到播放时长，但是下载到本地又是可以获取到播放时长的，只需要下载前 500 字节。
3. 我参考你的写法重新写了一版，写入临时文件后不删除临时文件，用临时文件的路径做参数，获取完文件播放时长后再删除临时文件。代码见 <https://github.com/hanxi/xiaomusic/blob/8bd32f878fda4c7a6d36e34738f6cbf872deed85/xiaomusic/utils.py#L169-L198>
4. 没去研究为什么传文件对象获取不到，可能有别的解法。
5. 是否需要提个 pr 把修改的函数合并过来呢？

**Comment by hanxi** [comment]
上面的 mp3 链接是这个 <http://music.163.com/song/media/outer/url?id=447925558.mp3> 经过 302 跳转拿到的，直接用这个会返回 json ，也没搞明白为啥。

**Comment by yihong0618** [comment]
我下午先研究下

**Comment by yihong0618** [comment]
@hanxi 你第一个链接 chrome 也拿不到时长好像。

**Comment by hanxi** [comment]
![Screenshot_2024-06-26-16-21-50-865_com android chrome](https://github.com/yihong0618/MiService/assets/1185757/ba52497a-2a8a-4284-84aa-dce6a920a691)

我这手机 chrome 上是能显示播放时长的

**Comment by yihong0618** [comment]
> ![Screenshot_2024-06-26-16-21-50-865_com android chrome](https://private-user-images.githubusercontent.com/1185757/343069889-ba52497a-2a8a-4284-84aa-dce6a920a691.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTA2NjcsIm5iZiI6MTcxOTM5MDM2NywicGF0aCI6Ii8xMTg1NzU3LzM0MzA2OTg4OS1iYTUyNDk3YS0yYThhLTQyODQtODRhYS1kY2U2YTkyMGE2OTEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjZUMDgyNjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWUwMWJiNDk4Yjk2MjEwYzMxMDdkYWI4ZWRkYmYyOTU1NWMyYzFlOTc3YmJmNjMyN2IyZTM5ZGFhNzlhZDIyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1wOuQub4yr4RGj4nzhCKrBFu9guAYepfFqnbQ_3x0TY)
> 
> 我这手机 chrome 上是能显示播放时长的

我的问题。。。

**Comment by yihong0618** [comment]
> > ![Screenshot_2024-06-26-16-21-50-865_com android chrome](https://private-user-images.githubusercontent.com/1185757/343069889-ba52497a-2a8a-4284-84aa-dce6a920a691.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzOTA2NjcsIm5iZiI6MTcxOTM5MDM2NywicGF0aCI6Ii8xMTg1NzU3LzM0MzA2OTg4OS1iYTUyNDk3YS0yYThhLTQyODQtODRhYS1kY2U2YTkyMGE2OTEuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjZUMDgyNjA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWUwMWJiNDk4Yjk2MjEwYzMxMDdkYWI4ZWRkYmYyOTU1NWMyYzFlOTc3YmJmNjMyN2IyZTM5ZGFhNzlhZDIyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1wOuQub4yr4RGj4nzhCKrBFu9guAYepfFqnbQ_3x0TY)
> > 我这手机 chrome 上是能显示播放时长的
> 
> 我的问题。。。

不是我的问题，换了几个环境浏览器都无法播放

**Comment by yihong0618** [comment]
必须走跳转才行。。。

**Comment by yihong0618** [comment]
https://m10.music.126.net/20240626132818/150ef0d02b16497727218fbc4046e46c/ymusic/5353/0f0f/0358/d99739615f8e5153d77042092f07fd77.mp3 这个 url 啥也没有
必须访问  http://music.163.com/song/media/outer/url?id=447925558.mp3  才能拿到一个新的 url

这个新的 url 会过期

**Comment by hanxi** [comment]
确实过期了，你可以用新的 url 测试。只是没搞明白为啥浏览器能拿到跳转的url，代码里却拿不到，难道是防爬的风控？

**Comment by yihong0618** [comment]
不是。。。我解决了你看看。

**Comment by yihong0618** [comment]
@hanxi 用最新的 commit 试试

**Comment by hanxi** [comment]
可以了，这样

**Comment by hanxi** [comment]
可以了，谢谢
