### ISSUE TITLE
from lingua import LanguageDetector已经找不到了

### ISSUE THREAD

**Issue by arbraham** [yihong0618/MiService#38]
这个lingua安装的是4.15，里面没有LanguageDetector，感觉这个库变了，不再是以前的了。

**Comment by yihong0618** [comment]
@frostming can you help to check?

**Comment by frostming** [comment]
抱歉哪里有lingua? 走错了repo?

**Comment by arbraham** [comment]
utils.py里用到的：

#!/usr/bin/env python3
from __future__ import annotations

import os
import re
import socket
from http.cookies import SimpleCookie
from typing import TYPE_CHECKING, AsyncIterator
from urllib.parse import urlparse

from requests.utils import cookiejar_from_dict
import math
if TYPE_CHECKING:
    from lingua import LanguageDetector
from langdetect import detect

**Comment by frostming** [comment]
@arbraham 就是走错门了啊，这是xiaogpt的

https://github.com/yihong0618/xiaogpt/blob/main/xiaogpt/utils.py

**Comment by arbraham** [comment]
抱歉提交错地方了。
